version: "3.8"

services:
    gbads_dash:
        build: ./TEV_dash
        restart: "always"
        ports:
            - "8051:8051"
        networks: 
            - gbads-app
networks: 
    gbads-app:
        driver: bridge



