name: Docker Build & ECS Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  docker:
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/docker.yml@main
    with: 
      IMAGE_NAME: tev-dash
      TAG: latest
      CONTEXT: ./dash
      DOCKERFILE: ./dash/Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  aws:
    needs: docker
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/aws.yml@main
    with: 
      SERVICE_NAME: TEV-dash-service
      CLUSTER_NAME: GBADs-Dashboards-Cluster
      AWS_REGION: us-east-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
